@startuml Контекстная диаграмма
title "Контекстная диаграмма системы бронирования отелей"

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"
!include $ICONURL/common.puml

Person(guest, "Гость", "Поиск и бронирование отелей")
Person(hotel, "Отель", "Управление бронированиями и отзывами")
Person(admin, "Администратор", "Модерация отзывов и управление системой")

Container(bookingSystem, "Система бронирования отелей","Централизованная система для поиска и бронирования отелей")

System_Ext(paymentAPI, "API платежных систем", "Обработка платежей")
System_Ext(notificationService, "Сервис уведомлений", "Отправка уведомлений пользователям")
System_Ext(externalAPI, "API внешних сервисов", "Интеграция с картами и другими сервисами")

Rel(guest, bookingSystem, "https", "Использует: Поиск отелей, бронирование, управление бронированиями, оставление отзывов")
Rel(hotel, bookingSystem, "https", "Использует: Добавление информации о номерах, управление бронированиями, ответы на отзывы, управление тарифами")
Rel(admin, bookingSystem, "https", "Использует: Модерация отзывов, управление списком отелей, аналитика")

Rel(bookingSystem, notificationService, "https", "Интеграция: Отправка уведомлений о бронированиях и акциях")
Rel(bookingSystem, paymentAPI, "https", "Интеграция: Обработка платежей за бронирования")
Rel(bookingSystem, externalAPI, "https", "Интеграция: Доступ к картам и другим внешним сервисам")

@enduml