@startuml
|Гость|
start

:Регистрация в системе;
:Создание профиля;

:Поиск отелей;
:Фильтрация по параметрам;
:Выбор отеля;

|Система|
:Поиск номеров по фильтрам;
if (Номера найдены?) then (да)
  else (нет)
    :Показать сообщение "Номера не найдены";
    end
endif

|Гость|
:Выбор номера;
:Выбор опции оплаты;

if (Опция оплаты) then (Предоплата) 
    |Система|
    :Показать экран с оплатой и информацией и брони;

    |Система|
    if (Оплата успешна?) then (да) 
        :Забронировать номер отеля;
        :Выслать чек подтверждения бронирования;
        :Показать экран с чеком и информацией о брони;
      else (нет) 
        :Показать экран о неуспешной оплате;
        :Показать кнопку для возврата на страницу оплаты;
        end
    endif
  else (Оплата на месте)
    |Система|
    :Показать экран с подтверждением брони и информацией о брони;

    if (Бронь подтверждена?) then (да) 
        :Выслать письмо с информацией о брони;
        :Показать экран с информацией о брони;
      else (нет)
        :Показываем кнопку для возврата на страницу поиска номера;
        end
    endif
endif

|Гость|
if (Гость прибыл в отель?) then (да)
    :Заселение;
    :Проживание в отеле;
    :Выезд из отеля;

    :Оставление отзыва;

    |Система|
    :Выслать уведомление отелю о новом отзыве;

    if (Отель ответил на отзыв?) then (да)
        :Выслать письмо гостю об ответе отеля;
      else (нет)
    endif

    |Гость|
    :Получение ответа от отеля;
    stop

  else (нет)
    |Система|
    :Отмена брони гостя (предоплата остается у отеля);
    :Выслать письмо гостю с уведомлением об отмене бронирования;
    end
endif


@enduml
