@startuml
|Гость|
start

:Регистрация в системе;
:Создание профиля;

:Поиск отелей;
:Фильтрация по параметрам;
:Выбор отеля;

|Система|
:Поиск номеров по фильрам;
:Проверка наличия номеров;

|Гость|
:Выбор номера;
:Выбор опции оплаты;

if (Опция оплаты) then (Предоплата)
  |Система|
  :Процесс предоплаты;
  if (Оплата успешна?) then (да)
    :Подтверждение бронирования;
    :Отправка подтверждения по email;
  else (нет)
    :Отображение ошибки оплаты;
  endif
else (Оплата на месте)
  :Бронирование номера с оплатой на месте;
  :Отправка подтверждения бронирования;
endif

|Гость|
:Прибытие в отель;
:Заселение;

:Проживание в отеле;
:Выезд из отеля;

:Оставление отзыва;

|Система|
:Отправка отзыва отелю;

|Гость|
:Получение ответа от отеля;

stop
@enduml
